import lifeinswe from "../images/eventGraphics/lifeinswe.png";
import infosession from "../images/eventGraphics/infosession.png";
import studyabroadinfosession from "../images/eventGraphics/studyabroadinfosession.png";

export const eventExpand = {
  "Welcome to WINC [WINC panel]": {
    type: "Recruitment",
    time: "2:30PM",
    link: "https://ucr.zoom.us/j/99937718388",
    date: "September 21, 2021 2:30PM",
    desc: "Learn more about what our club has to offer and to get a chance to ask our board members any of your questions.",
    day: "21",
    month: "SEP",
    endDate: new Date("Tue, 21 Sep 2021 19:51:00 -0700"),
  },
  "Dealing with Hybrid Classes": {
    type: "Recruitment",
    time: "2:30PM",
    link: "https://ucr.zoom.us/j/92367209083?pwd=eWhNS21UR1l1UGZLczJtSUFsY1FRdz09",
    date: "September 27, 2021 2:30PM",
    desc: "Learn how to be successful with hybrid classes, how to make friends, and how to utilize the resources UCR has to offer.",
    day: "27",
    month: "SEP",
    endDate: new Date("2021-09-27T15:00:00-0700"),
  },
  "Land That SWE Internship & Intern AMA": {
    type: "General Meeting",
    time: "7:00PM",
    link: "https://ucr.zoom.us/j/96741730329",
    date: "October 05, 2021 7:00PM",
    desc: "Learn all the tips & tricks to get your foot in the door in the tech industry. Chat with WINC members who used these tips to land their dream internships at some of the hottest tech companies today!",
    day: "05",
    month: "OCT",
    endDate: new Date("2021-10-05T19:51:00-0700"),
  },
  "How to Make the Best of your Summer": {
    type: "Technical Workshop",
    time: "5:30PM",
    link: "https://us02web.zoom.us/j/7181383962",
    date: "October 12, 2021 5:30PM",
    desc: "What will you be doing next summer? An internship, research, classes? Advice on how to set yourself up early so that you make the best of your summer.",
    day: "12",
    month: "OCT",
    endDate: new Date("2021-10-12T19:00:00-0700"),
  },
  "Virtual Social/GameNight": {
    type: "Social",
    time: "7:00PM",
    link: "https://ucr.zoom.us/j/93855431885?pwd=Q3hsVE85bmhDRUY5Tm56bE1iUlBYQT09#success",
    date: "October 12, 2021 7:00PM",
    desc: "Take a break from school and get to know your fellow peers by joining WINC for our first social! Get ready for some friendly competition.",
    day: "12",
    month: "OCT",
    endDate: new Date("2021-10-12T19:51:00-0700"),
  },
  "Fireside Chat with Professor LePendu": {
    type: "Fireside Chats",
    time: "7:00PM",
    link: "https://us02web.zoom.us/j/7181383962",
    date: "November 02, 2021 7:00PM",
    desc: "Ever wanted to have the opportunity to have a more informal conversation with a UCR Computer Science professor? Well now you have the opportunity to do so. Come join us in or Fireside Chat with our special guest Professor LePendu! We can't wait to see you there and hear your questions!",
    day: "02",
    month: "NOV",
    endDate: new Date("2021-11-02T20:00:00-0700"),
  },
  "Intro to LinkedIn @ Cutie Hack": {
    type: "Technical Workshop",
    time: "TBD",
    link: "",
    desc: "details coming soon",
    date: "November 06, 2021 TBD",
    day: "06",
    month: "NOV",
    endDate: new Date("2021-11-06T19:51:00-0700"),
  },
  "Sharpen Soft Skills at a Graduate Level": {
    type: "Graduate Session",
    time: "7:00PM",
    link: "https://ucr.zoom.us/j/93690075538",
    date: "November 09, 2021 7:00PM",
    desc: "Want to learn a few soft skills expected of a current or a future graduate student in academic and non-academic settings such as communication, critical thinking, research and teaching management and so on? Come out to WINC's first graduate student session this quarter, and find out while also connecting with other graduate students in the process.",
    day: "09",
    month: "NOV",
    endDate: new Date("2021-11-09T19:51:00-0700"),
  },
  "Industry Professional Panel": {
    type: "Panel",
    time: "7:00PM",
    link: "https://ucr.zoom.us/j/94431789755?pwd=RWdmaTZnQWFHM0hGSllKOHJUTVltZz09",
    date: "November 11, 2021 7:00PM",
    desc: "Interested in learning more about work in the tech industry? Come out to our Industry Professional Panel to meet industry professionals, hear about their experiences and ask any questions you have!",
    day: "11",
    month: "NOV",
    endDate: new Date("2021-11-11T20:00:00-0700"),
  },
  "World of Computing": {
    type: "General Meeting",
    time: "7:00PM",
    link: "https://ucr.zoom.us/j/96714866468",
    date: "November 16, 2021 7:00PM",
    desc: "Explore the possible career paths in tech. Coding background isn't needed to work in tech, so come on by to discover what awaits for you online.",
    day: "16",
    month: "NOV",
    endDate: new Date("2021-11-16T19:51:00-0700"),
  },
  "Officer Infosession": {
    type: "Infosession",
    time: "7:00PM",
    link: "https://ucr.zoom.us/j/93062426739",
    date: "January 5, 2022 7:00PM",
    desc: "Interested in the behind-the scenes action at WINC? Stop by our Officer Infosession to learn about all of our new positions and how to apply!",
    day: "05",
    month: "JAN",
    endDate: new Date("2022-01-05T19:51:00-0700"),
    src: infosession,
  },
  "Rose Hack: Resume Workshop": {
    type: "Other",
    time: "5:00PM",
    link: "",
    date: "January 12, 2022 5:00PM",
    desc: "",
    day: "12",
    month: "JAN",
    endDate: new Date("2022-01-12T17:51:00-0700"),
  },
  "Life in the Industry: SWE": {
    type: "General Meeting",
    time: "7:00PM",
    link: "https://ucr.zoom.us/j/92395237310",
    date: "January 12, 2022 7:00PM",
    desc: "Introducing our Life in the Industry series: Learn all about the innerworkings of specific tech career paths and how the day to day life the opportunity entails. We will first explore the SWE role, and what a post-grad life looks like for this position.",
    day: "12",
    month: "JAN",
    src: lifeinswe,
    endDate: new Date("2022-01-12T19:51:00-0700"),
  },
  "WINC: Study Abroad Infosession": {
    type: "Infosession",
    time: "7:00PM",
    link: "https://ucr.zoom.us/j/95839206307",
    date: "January 13, 2022 7:00PM",
    desc: "Love software engineering? Love Paris? Check out UCR's new Startup Bootcamp program hosted by Prof. Jeff McDaniel and Prof. Brian Crites this summer! Take CS110 and CS175 in Paris, France this July during Summer Sessions and learn about how pitch a tech business idea with an international perspective. Have questions? Please stop by our infosession to meet the instructors and more info! Link to Startup Bootcamp Information: https://bit.ly/3IJcN4A",
    day: "13",
    month: "JAN",
    src: studyabroadinfosession,
    endDate: new Date("2022-01-13T19:51:00-0700"),
  },
  "What is the Internet of Things (IoT)?": {
    type: "Technical Workshop",
    time: "7:00PM",
    link: "https://ucr.zoom.us/j/6347811852",
    date: "January 19, 2022 7:00PM",
    desc: "Have you ever heard the term Internet of Things or IoT and were curious about what it is? Join us in this workshop to learn about IoT and why it is the next big revolution in computing.",
    day: "19",
    month: "JAN",
    endDate: new Date("2022-01-19T19:51:00-0700"),
  },
  "Speed Friending Social": {
    type: "Social",
    time: "7:00PM",
    link: "https://ucr.zoom.us/j/91629746767",
    date: "January 26, 2022 7:00PM",
    desc: "Feeling stressed about midterms? Looking to make more friends in WINC? You’ve come to the right place! Join WINC on Wednesday, January 26th at 7PM PST for a fun Speed Friending Social! Be ready to play games and socialize with others. We hope to see you all there!",
    day: "26",
    month: "JAN",
    endDate: new Date("2022-01-26T19:51:00-0700"),
  },
  "How to Apply to Graduate School": {
    type: "Graduate Session",
    time: "7:00PM",
    link: "https://ucr.zoom.us/j/94921620784",
    date: "February 2, 2022 7:00PM",
    desc: "Interested in applying to grad school or learning how it is like being a grad student? Learn some tips and tricks from a graduate student who has gone through the process. For our second graduate session of the year, let us show you some insights into graduate school and its application process. We hope to see you there!",
    day: "02",
    month: "FEB",
    endDate: new Date("2022-02-02T19:51:00-0700"),
  },
  "Virtual Reality and the Metaverse": {
    type: "Technical Workshop",
    time: "7:00PM",
    link: "https://ucr.zoom.us/j/6347811852",
    date: "February 9, 2022 7:00PM",
    desc: "When Meta (formerly Facebook) came out saying that Meta will be delving into creating a Metaverse, I’m sure we were all curious and confused about the company shift. In this workshop, we will be talking about Virtual Reality and the Metaverse and why it is something to learn more about.",
    day: "09",
    month: "FEB",
    endDate: new Date("2022-02-09T19:51:00-0700"),
  },
  "Fireside Chat with Dr. Salloum": {
    type: "Fireside Chats",
    time: "7:00PM",
    link: "https://ucr.zoom.us/j/94596661949",
    date: "February 16, 2022 7:00PM",
    desc: "Want to learn how you can gain more experience in the industry? Join us in our fireside chat as we talk to UCR professor Dr. Salloum on how students can get ahead.\nAttend our Fireside chat on February 16th at 7:00pm to ask questions and talk to one of our beloved professors. We can’t wait to see you there!",
    day: "16",
    month: "FEB",
    endDate: new Date("2022-02-16T19:51:00-0700"),
  },
  "Life in the Industry: PM": {
    type: "General Meeting",
    time: "7:00PM",
    link: "https://ucr.zoom.us/j/99106462516",
    date: "February 23, 2022 7:00PM",
    desc: "For our second installment of the Life in the Industry series: Learn all about the role as a Product Manager, from the details of the day-to-day work schedule to the ranking status, salaries, and the people you work with in this position.",
    day: "23",
    month: "FEB",
    endDate: new Date("2022-02-23T19:51:00-0700"),
  },
  "From  College Students to Software Engineers": {
    type: "Industry Professional Panel",
    time: "7:00PM",
    link: "https://ucr.zoom.us/j/96068293977",
    date: "March 2, 2022 7:00PM",
    desc: "Moving on from college and into the real world can be scary. Luckily, recent college graduates and current software engineers Katie Fukuda, Paris Hom, and Wendy Li are here to answer all your questions about transitioning to post-grad life! Come out to our Industry Professional Panel to hear about our speakers’ experiences and ask any questions you have!",
    day: "2",
    month: "MAR",
    endDate: new Date("2022-03-02T19:51:00-0700"),
  },
};
