export const eventExpand = {
  "Welcome to WINC [WINC panel]": {
    type: "Recruitment",
    time: "2:30PM",
    link: "https://ucr.zoom.us/j/99937718388",
    desc: "Learn more about what our club has to offer and to get a chance to ask our board members any of your questions.",
    day: "21",
    month: "SEP",
    endDate: new Date("Tue, 21 Sep 2021 19:51:00 -0700"),
  },
  "Dealing with Hybrid Classes": {
    type: "Recruitment",
    time: "2:30PM",
    link: "https://ucr.zoom.us/j/92367209083?pwd=eWhNS21UR1l1UGZLczJtSUFsY1FRdz09",
    desc: "Learn how to be successful with hybrid classes, how to make friends, and how to utilize the resources UCR has to offer.",
    day: "27",
    month: "SEP",
    endDate: new Date("2021-09-27T15:00:00-0700"),
  },
  "Land That SWE Internship & Intern AMA": {
    type: "General Meeting",
    time: "7:00PM",
    link: "https://ucr.zoom.us/j/96741730329",
    desc: "Learn all the tips & tricks to get your foot in the door in the tech industry. Chat with WINC members who used these tips to land their dream internships at some of the hottest tech companies today!",
    day: "05",
    month: "OCT",
    endDate: new Date("2021-10-05T19:51:00-0700"),
  },
  "How to Make the Best of your Summer": {
    type: "Technical Workshop",
    time: "TBD",
    link: "https://us02web.zoom.us/j/7181383962",
    desc: 'What will you be doing next summer? An internship, research, classes? Advice on how to set yourself up early so that you make the best of your summer.',
    day: "12",
    month: "OCT",
    endDate: new Date("2021-10-13T00:00:00-0700"),
  },
  "Virtual Social/GameNight": {
    type: "Social",
    time: "7:00PM",
    link: "https://ucr.zoom.us/j/93855431885?pwd=Q3hsVE85bmhDRUY5Tm56bE1iUlBYQT09#success",
    desc: 'Take a break from school and get to know your fellow peers by joining WINC for our first social! Get ready for some friendly competition.',
    day: "12",
    month: "OCT",
    endDate: new Date("2021-10-12T19:51:00-0700"),
  },
  "Industry Professional Panel": {
    type: "Panel",
    time: "TBD",
    link: "",
    desc: 'details coming soon',
    day: "19",
    month: "OCT",
    endDate: new Date("2021-10-12T19:00:00-0700"),
  },
  "Cutie Hack": {
    type: "Technical Workshop",
    time: "TBD",
    link: "",
    desc: 'details coming soon',
    day: "06",
    month: "NOV",
    endDate: new Date("2021-11-06T19:51:00-0700"),
  },
  "Scientific Communication in Computing": {
    type: "Graduate Session",
    time: "7:00PM",
    link: "https://ucr.zoom.us/j/93690075538",
    desc: "Learn how to communicate in science and computing at a graduate level, and connect with other graduate students in the process",
    day: "09",
    month: "NOV",
    endDate: new Date("2021-11-09T19:51:00-0700"),
  },
  "World of Computing": {
    type: "General Meeting",
    time: "7:00PM",
    link: "https://ucr.zoom.us/j/96714866468",
    desc: 'Explore the possible career paths in tech. Coding background isn\'t needed to work in tech, so come on by to discover what awaits for you online.',
    day: "16",
    month: "NOV",
    endDate: new Date("2021-11-16T19:51:00-0700"),
  },
  "Intro to Git/Github": {
    type: "General Meeting",
    time: "TBD",
    link: "https://us02web.zoom.us/j/7181383962",
    desc: 'Want to know how to use GitHub and Git efficiently and effectively? Stop by this workshop to learn some Github and Git tips and tricks.',
    day: "23",
    month: "NOV",
    endDate: new Date("2021-11-24T00:00:00-0700"),
  },
};
